import { Company } from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'BLUEGEM IT SOLUTIONS PRIVATE LIMITED',
    industry: 'IT Solutions',
    location: 'HYDERABAD',
    website: 'WWW.BIZ-E-WEB.COM',
    established: '2014-11-08',
    description: 'Premier IT Solutions provider specializing in digital transformation.',
    slots: [{ id: 's1-1', isBooked: false }, { id: 's1-2', isBooked: false }, { id: 's1-3', isBooked: false }],
  },
  {
    id: 'c2',
    name: 'NEXTQBICLE SOFTWARE TECHNOLOGIES PRIVATE LIMITED',
    industry: 'Software Technologies',
    location: 'HYDERABAD',
    website: 'WWW.NCKTECH.CO',
    established: '2017-02-16',
    description: 'Innovative software technology firm delivering next-gen solutions.',
    slots: [{ id: 's2-1', isBooked: false }, { id: 's2-2', isBooked: false }, { id: 's2-3', isBooked: false }],
  },
  {
    id: 'c3',
    name: 'YOULOGIX INFOTECH PRIVATE LIMITED',
    industry: 'Infotech',
    location: 'Bangalore , Delhi',
    website: 'logixitcore.com',
    established: '2013-03-04',
    description: 'Strategic infotech services across major tech hubs.',
    slots: [{ id: 's3-1', isBooked: false }, { id: 's3-2', isBooked: false }, { id: 's3-3', isBooked: false }],
  },
  {
    id: 'c4',
    name: 'GLOBUS INFO SERVICES PRIVATE LIMITED',
    industry: 'Info Services',
    location: 'Bangalore , Delhi',
    website: 'www.infoecon.net',
    established: '2013-06-04',
    description: 'Global information services and economic consulting.',
    slots: [{ id: 's4-1', isBooked: false }, { id: 's4-2', isBooked: false }, { id: 's4-3', isBooked: false }],
  },
  {
    id: 'c5',
    name: 'SCANFII SOFTWARE TECHNOLOGIES',
    industry: 'Software Technologies',
    location: 'Bangalore',
    website: 'www.stlpg.com',
    established: '2016-02-12',
    description: 'Cutting-edge software technologies and platform development.',
    slots: [{ id: 's5-1', isBooked: false }, { id: 's5-2', isBooked: false }, { id: 's5-3', isBooked: false }],
  },
  {
    id: 'c6',
    name: 'INVENTUS INFO CONSULTING',
    industry: 'Consulting',
    location: 'Bangalore',
    website: 'www.inventmea.com',
    established: '2017-02-16',
    description: 'Expert information consulting for enterprise growth.',
    slots: [{ id: 's6-1', isBooked: false }, { id: 's6-2', isBooked: false }, { id: 's6-3', isBooked: false }],
  },
  {
    id: 'c7',
    name: 'BMS INFOSOLUTIONS PRIVATE LIMITED',
    industry: 'Infosolutions',
    location: 'Bangalore and Mumbai',
    website: 'WWW.TIBMS.COM',
    established: '2013-12-17',
    description: 'Comprehensive info-solutions connecting key markets.',
    slots: [{ id: 's7-1', isBooked: false }, { id: 's7-2', isBooked: false }, { id: 's7-3', isBooked: false }],
  },
  {
    id: 'c8',
    name: 'ADROLA SOFTWARE TECHNOLOGIES INDIA PRIVATE LIMITED',
    industry: 'Software Technologies',
    location: 'Bangalore and Mumbai',
    website: 'www.adroitteam.com',
    established: '2013-04-02',
    description: 'Software excellence driving business value in India.',
    slots: [{ id: 's8-1', isBooked: false }, { id: 's8-2', isBooked: false }, { id: 's8-3', isBooked: false }],
  },
];