import React, { useState } from 'react';
import { X, Share2, Mail, Copy, Check, Facebook, Instagram, MessageCircle } from 'lucide-react';
import { RegistrationFormData } from '../types';
import { jsPDF } from 'jspdf';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  bookingDetails: {
    companyName: string;
    designation: string;
    candidateName: string;
    registrationDetails?: RegistrationFormData;
  } | null;
}

const ShareModal: React.FC<ShareModalProps> = ({ isOpen, onClose, bookingDetails }) => {
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen || !bookingDetails) return null;

  const shareUrl = window.location.href;
  const shortText = `I've registered for ${bookingDetails.designation} at ${bookingDetails.companyName} via AIKYA-AI Infotech!`;
  
  const handleCopy = () => {
    navigator.clipboard.writeText(`${shortText}\n${shareUrl}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generatePDF = () => {
    if (!bookingDetails.registrationDetails) return;

    setIsGenerating(true);
    const doc = new jsPDF();
    const data = bookingDetails.registrationDetails;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(15, 23, 42); // Primary dark blue
    doc.text("Registration Confirmation", 105, 20, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("AIKYA-AI Infotech PVT LTD", 105, 28, { align: "center" });

    doc.setDrawColor(200);
    doc.line(20, 35, 190, 35);

    // Content
    let y = 50;
    const lineHeight = 10;
    const leftColX = 20;
    const rightColX = 110;

    doc.setFontSize(10);
    doc.setTextColor(0);

    const addField = (label: string, value: string, col: 'left' | 'right' | 'full' = 'left') => {
        const x = col === 'right' ? rightColX : leftColX;
        const displayValue = value || 'N/A';
        
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, x, y);
        
        doc.setFont("helvetica", "normal");
        // Simple text wrapping handling for full width
        if (col === 'full') {
            doc.text(displayValue, x + 40, y, { maxWidth: 130 });
            y += lineHeight; 
        } else {
             doc.text(displayValue, x + 40, y);
        }
    };

    // Personal Details
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Personal Details", 20, y);
    y += 10;
    doc.setFontSize(10);
    
    addField("Full Name", data.fullName, 'left');
    addField("Company", data.companyName, 'right');
    y += lineHeight;
    
    addField("Father Name", data.fatherName, 'left');
    addField("Mother Name", data.motherName, 'right');
    y += lineHeight;

    addField("DOB", data.dob, 'left');
    addField("Gender", data.gender, 'right');
    y += lineHeight;

    addField("PAN", data.panNumber, 'left');
    addField("Status", data.marriageStatus, 'right');
    y += lineHeight;

    y += 5;
    addField("Address", data.permanentAddress, 'full');
    y += 5;

    // Employment
    y += 10;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Employment Details", 20, y);
    y += 10;
    doc.setFontSize(10);

    addField("Designation", data.joiningDesignation, 'left');
    addField("CTC", data.joiningCTC, 'right');
    y += lineHeight;

    addField("Joining Date", data.joiningDate, 'left');
    addField("Experience", data.currentDesignation, 'right');
    y += lineHeight;

    // Bank
    y += 10;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Banking Details", 20, y);
    y += 10;
    doc.setFontSize(10);

    addField("Bank", data.bankName, 'left');
    addField("Account", data.bankAccountNumber, 'right');
    y += lineHeight;
    addField("IFSC", data.bankIFSCCode, 'left');

    // Footer
    y = 280;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by AIKYA-AI Infotech Booking System", 105, y, { align: "center" });

    doc.save(`${data.fullName.replace(/\s+/g, '_')}_Registration.pdf`);
    setIsGenerating(false);
    return true;
  };

  const getFormattedWhatsAppMessage = (data: RegistrationFormData) => {
    return `*REGISTRATION FORM DETAILS*
--------------------------------
*Company Name:* ${data.companyName}
*Full Name:* ${data.fullName}
*Father Name:* ${data.fatherName}
*Mother Name:* ${data.motherName}
*PAN Number:* ${data.panNumber}
*Date Of Birth:* ${data.dob}
*UAN Number:* ${data.uanNumber}
*Address:* ${data.permanentAddress}

*EMPLOYMENT DETAILS*
*Offer Date:* ${data.offerDate}
*Joining Date:* ${data.joiningDate}
*Joining CTC:* ${data.joiningCTC}
*Joining Designation:* ${data.joiningDesignation}
*Hike Date:* ${data.hikeDate || 'N/A'}
*Current CTC:* ${data.currentCTC}
*Current Designation:* ${data.currentDesignation}
*Resignation Date:* ${data.resignationDate || 'N/A'}
*Reliving Date:* ${data.relivingDate || 'N/A'}
*PF Required:* ${data.pfRequired}

*EDUCATION*
*Qualification:* ${data.highestQualification}
*Year of Pass:* ${data.yearOfPass}
*Technology:* ${data.technology}

*BANKING DETAILS*
*Bank Name:* ${data.bankName}
*Account No:* ${data.bankAccountNumber}
*Branch:* ${data.bankBranch}
*IFSC Code:* ${data.bankIFSCCode}

*Gender:* ${data.gender}
*Marriage Status:* ${data.marriageStatus}
--------------------------------
Generated via AIKYA-AI Infotech`;
  };

  const handleShare = async (platform: 'whatsapp' | 'email' | 'facebook' | 'instagram') => {
    let url = '';

    switch (platform) {
      case 'whatsapp':
        if (bookingDetails.registrationDetails) {
            // Generate the structured text message
            const message = getFormattedWhatsAppMessage(bookingDetails.registrationDetails);
            
            // Open WhatsApp directly with the text message (No PDF download)
            url = `https://wa.me/?text=${encodeURIComponent(message)}`;
            window.open(url, '_blank');
        } else {
             // Fallback if no details
             url = `https://wa.me/?text=${encodeURIComponent(shortText + ' ' + shareUrl)}`;
             window.open(url, '_blank');
        }
        break;
      case 'email':
        url = `mailto:?subject=${encodeURIComponent('My Booking Confirmation - AIKYA-AI')}&body=${encodeURIComponent(shortText + '\n\n' + shareUrl)}`;
        window.location.href = url;
        break;
      case 'facebook':
        url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shortText)}`;
        window.open(url, '_blank');
        break;
      case 'instagram':
        handleCopy();
        setTimeout(() => {
          window.open('https://www.instagram.com/', '_blank');
        }, 500);
        break;
    }
  };

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden border border-gray-100 transform transition-all">
        
        {/* Header */}
        <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
          <h3 className="font-bold text-gray-800 flex items-center gap-2">
            <Share2 size={18} className="text-accent" />
            Share Registration
          </h3>
          <button onClick={onClose} className="p-1 text-gray-400 hover:text-red-500 rounded-full transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 mb-6 relative group">
            <p className="text-gray-600 text-sm italic leading-relaxed">
                "{shortText}"
            </p>
            <button 
                onClick={handleCopy}
                className="absolute top-2 right-2 p-1.5 bg-white rounded-lg shadow-sm text-gray-400 hover:text-accent transition-colors"
                title="Copy text"
            >
                {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
            </button>
            {copied && <span className="absolute -top-8 right-0 text-xs bg-black text-white px-2 py-1 rounded">Copied!</span>}
          </div>

          <div className="grid grid-cols-2 gap-4">
            {/* WhatsApp - Primary Action */}
            <button 
                onClick={() => handleShare('whatsapp')}
                className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl bg-[#25D366]/10 text-[#25D366] hover:bg-[#25D366] hover:text-white transition-all font-medium border border-[#25D366]/20 col-span-2 shadow-sm"
            >
                <div className="flex items-center gap-2">
                    <MessageCircle size={24} /> 
                    <span className="text-lg">Share on WhatsApp</span>
                </div>
                <span className="text-[10px] opacity-80 flex items-center gap-1">
                    Sends registration details as text
                </span>
            </button>

            <button 
                onClick={() => handleShare('facebook')}
                className="flex items-center justify-center gap-2 p-3 rounded-xl bg-[#1877F2]/10 text-[#1877F2] hover:bg-[#1877F2] hover:text-white transition-all font-medium"
            >
                <Facebook size={20} /> Facebook
            </button>

            <button 
                onClick={() => handleShare('instagram')}
                className="flex items-center justify-center gap-2 p-3 rounded-xl bg-[#E4405F]/10 text-[#E4405F] hover:bg-[#E4405F] hover:text-white transition-all font-medium group relative"
            >
                <Instagram size={20} /> Instagram
            </button>

            <button 
                onClick={() => handleShare('email')}
                className="flex items-center justify-center gap-2 p-3 rounded-xl bg-gray-100 text-gray-600 hover:bg-gray-800 hover:text-white transition-all font-medium col-span-2"
            >
                <Mail size={20} /> Email
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ShareModal;